import learningsSlice from "../slices/learningsSlice";

export const {
  fetchLearningCategoriesRequest,
  fetchLearningCategoriesSuccess,
  fetchLearningCategoriesFailure,
  addLearningCategoryRequest,
  addLearningCategorySuccess,
  addLearningCategoryFailure,
  fetchLearningByCategoryRequest,
  fetchLearningByCategorySuccess,
  fetchLearningByCategoryFailure,
  addLearningArticleRequest,
  addLearningArticleSuccess,
  addLearningArticleFailure,
  editLearningArticleRequest,
  editLearningArticleSuccess,
  editLearningArticleFailure,
  deleteLearningArticleRequest,
  deleteLearningArticleSuccess,
  deleteLearningArticleFailure,
  fetchLearningArticleRequest,
  fetchLearningArticleSuccess,
  fetchLearningArticleFailure,
  addLearningCommentRequest,
  addLearningCommentSuccess,
  addLearningCommentFailure,
  clearLearningCategoryErrors,
  clearLearningArticleErrors
} = learningsSlice.actions;