import tripsSlice from "../slices/tripsSlice";

export const {
  fetchTripsRequest,
  fetchTripsSuccess,
  fetchTripsFailure,
  fetchTripsByCarrierRequest,
  fetchTripsByCarrierSuccess,
  fetchTripsByCarrierFailure,
  createTripRequest,
  createTripSuccess,
  createTripFailure,
  changeTripStatusRequest,
  changeTripStatusSuccess,
  changeTripStatusFailure,
  cancelTripRequest,
  cancelTripSuccess,
  cancelTripFailure,
  fetchTripRequest,
  fetchTripSuccess,
  fetchTripFailure,
  editTripRequest,
  editTripSuccess,
  editTripFailure,
  addCommentRequest,
  addCommentSuccess,
  addCommentFailure,
  addAttachmentRequest,
  addAttachmentSuccess,
  addAttachmentFailure,
  confirmTripsRequest,
  confirmTripsSuccess,
  confirmTripsFailure,
  clearCreateTripErrorRequest,
  fetchWeekTripsRequest,
  fetchWeekTripsSuccess,
  fetchWeekTripsFailure,
  searchTripsRequest,
  searchTripsSuccess,
  searchTripsFailure
} = tripsSlice.actions;